# Generated by Django 5.1.15 on 2025-12-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socio',
            new_name='Tarea',
        ),
    ]
